AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: VisitJo - Update template that deploys Lambdas and API. Reuses existing S3/DynamoDB/API when provided.

Parameters:
  ExistingBucketName:
    Type: String
    Default: ''
    Description: Existing S3 bucket name to reuse. Leave empty to create a new bucket.
  ExistingTableName:
    Type: String
    Default: ''
    Description: Existing DynamoDB table name to reuse. Leave empty to create a new table.
  ExistingApiId:
    Type: String
    Default: ''
    Description: Existing API Gateway RestApiId to attach endpoints to. Leave empty to create a new API.
  CognitoUserPoolArn:
    Type: String
    Default: ''
    Description: ARN of existing Cognito User Pool (optional).
  AllowedOrigins:
    Type: CommaDelimitedList
    Default: "http://localhost:5175"
    Description: Comma-separated list of allowed origins for CORS (frontend hosts)

Conditions:
  UseExistingBucket: !Not [!Equals [!Ref ExistingBucketName, '']]
  UseExistingTable: !Not [!Equals [!Ref ExistingTableName, '']]
  UseExistingApi: !Not [!Equals [!Ref ExistingApiId, '']]
  HasCognitoArn: !Not [!Equals [!Ref CognitoUserPoolArn, '']]

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 20
    MemorySize: 512

Resources:
  # Only create these if not provided
  UserImagesBucket:
    Type: AWS::S3::Bucket
    Condition: !Not [UseExistingBucket]
    Properties:
      BucketName: !Sub "visitjo-user-images-${AWS::AccountId}-${AWS::Region}"
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: !Ref AllowedOrigins
            AllowedMethods: [GET, PUT, POST, HEAD]
            AllowedHeaders: ['*']
            MaxAge: 3000
    DeletionPolicy: Retain

  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Condition: !Not [UseExistingTable]
    Properties:
      TableName: !Sub "VisitJo-UserProfiles-${AWS::AccountId}-${AWS::Region}"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    DeletionPolicy: Retain

  VisitJoApi:
    Type: AWS::Serverless::Api
    Condition: !Not [UseExistingApi]
    Properties:
      Name: VisitJoApi
      StageName: prod
      Cors: 
        AllowMethods: "OPTIONS,GET,PUT,POST"
        AllowHeaders: "Content-Type,Authorization"
        AllowOrigin: !Join [",", !Ref AllowedOrigins]
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !If [HasCognitoArn, !Ref CognitoUserPoolArn, !Ref "AWS::NoValue"]

  PresignFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitjo-presign-upload
      Handler: index.handler
      CodeUri: ../presign-upload/
      Environment:
        Variables:
          BUCKET_NAME: !If [UseExistingBucket, !Ref ExistingBucketName, !Ref UserImagesBucket]
      Policies:
        - Statement:
            - Effect: Allow
              Action: [s3:PutObject, s3:GetObject, s3:ListBucket]
              Resource:
                - !If [UseExistingBucket, !Sub "arn:aws:s3:::${ExistingBucketName}", !Sub "arn:aws:s3:::${UserImagesBucket}"]
                - !If [UseExistingBucket, !Sub "arn:aws:s3:::${ExistingBucketName}/*", !Sub "arn:aws:s3:::${UserImagesBucket}/*"]
      Events: !If
        - UseExistingApi
        - {}  # No events when using existing API
        - PresignUploadApi:  # Only add events when creating new API
            Type: Api
            Properties:
              Path: /uploads/signed-url
              Method: post
              RestApiId: !Ref VisitJoApi

  UserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitjo-user-profile
      Handler: index.handler
      CodeUri: ../user-profile/
      Environment:
        Variables:
          TABLE_NAME: !If [UseExistingTable, !Ref ExistingTableName, !Ref UserProfilesTable]
          BUCKET_NAME: !If [UseExistingBucket, !Ref ExistingBucketName, !Ref UserImagesBucket]
      Policies:
        - Statement:
            - Effect: Allow
              Action: [dynamodb:GetItem, dynamodb:PutItem, dynamodb:UpdateItem, dynamodb:Query]
              Resource: !If [UseExistingTable, !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ExistingTableName}", !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${UserProfilesTable}"]
            - Effect: Allow
              Action: [s3:GetObject]
              Resource:
                - !If [UseExistingBucket, !Sub "arn:aws:s3:::${ExistingBucketName}/*", !Sub "arn:aws:s3:::${UserImagesBucket}/*"]
      Events: !If
        - UseExistingApi
        - {}  # No events when using existing API
        - GetUserProfileApi:  # Only add events when creating new API
            Type: Api
            Properties:
              Path: /user/profile
              Method: get
              RestApiId: !Ref VisitJoApi
          PutUserProfileApi:
            Type: Api
            Properties:
              Path: /user/profile
              Method: put
              RestApiId: !Ref VisitJoApi

Outputs:
  ApiUrl:
    Description: "Base URL for API"
    Value: !If [UseExistingApi, !Sub "https://${ExistingApiId}.execute-api.${AWS::Region}.amazonaws.com/prod", !Sub "https://${VisitJoApi}.execute-api.${AWS::Region}.amazonaws.com/prod"]
  BucketName:
    Description: S3 bucket name for user images
    Value: !If [UseExistingBucket, !Ref ExistingBucketName, !Ref UserImagesBucket]
  TableName:
    Description: DynamoDB table name for user profiles
    Value: !If [UseExistingTable, !Ref ExistingTableName, !Ref UserProfilesTable]
  PresignFunctionArn:
    Description: Presign Lambda ARN
    Value: !GetAtt PresignFunction.Arn
  UserProfileFunctionArn:
    Description: User profile Lambda ARN
    Value: !GetAtt UserProfileFunction.Arn
