AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: VisitJo preferences + uploads SAM template (S3, DynamoDB, Lambdas, API)

Parameters:
  CognitoUserPoolArn:
    Type: String
    Default: ''
    Description: ARN of existing Cognito User Pool (optional). If provided, API will require Cognito auth.
  AllowedOrigins:
    Type: CommaDelimitedList
    Default: "http://localhost:5175"
    Description: Comma-separated list of allowed origins for CORS (frontend hosts)

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 20
    MemorySize: 512

Resources:
  UserImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "visitjo-user-images-${AWS::AccountId}-${AWS::Region}"
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: !Ref AllowedOrigins
            AllowedMethods: [GET, PUT, POST, HEAD]
            AllowedHeaders: ['*']
            MaxAge: 3000
    DeletionPolicy: Retain

  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "VisitJo-UserProfiles-${AWS::AccountId}-${AWS::Region}"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    DeletionPolicy: Retain

  VisitJoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: VisitJoApi
      StageName: prod
      Cors: 
        AllowMethods: "OPTIONS,GET,PUT,POST"
        AllowHeaders: "Content-Type,Authorization"
        AllowOrigin: !Join [",", !Ref AllowedOrigins]
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            # If CognitoUserPoolArn parameter empty, this will be ignored in practice; deploy will still create API without enforced authorizer unless set by you.
            UserPoolArn: !If [HasCognitoArn, !Ref CognitoUserPoolArn, !Ref "AWS::NoValue"]

  PresignFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitjo-presign-upload
      Handler: index.handler
      CodeUri: ../presign-upload/
      Environment:
        Variables:
          BUCKET_NAME: !Ref UserImagesBucket
      Events:
        PresignUploadApi:
          Type: Api
          Properties:
            Path: /uploads/signed-url
            Method: post
            RestApiId: !Ref VisitJoApi

  UserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitjo-user-profile
      Handler: index.handler
      CodeUri: ../user-profile/
      Environment:
        Variables:
          TABLE_NAME: !Ref UserProfilesTable
      Events:
        GetUserProfileApi:
          Type: Api
          Properties:
            Path: /user/profile
            Method: get
            RestApiId: !Ref VisitJoApi
        PutUserProfileApi:
          Type: Api
          Properties:
            Path: /user/profile
            Method: put
            RestApiId: !Ref VisitJoApi

Conditions:
  HasCognitoArn: !Not [!Equals [!Ref CognitoUserPoolArn, ""]]

Outputs:
  ApiUrl:
    Description: "Base URL for API"
    Value: !Sub "https://${VisitJoApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  BucketName:
    Description: S3 bucket name for user images
    Value: !Ref UserImagesBucket
  TableName:
    Description: DynamoDB table name for user profiles
    Value: !Ref UserProfilesTable
  PresignFunctionArn:
    Description: Presign Lambda ARN
    Value: !GetAtt PresignFunction.Arn
  UserProfileFunctionArn:
    Description: User profile Lambda ARN
    Value: !GetAtt UserProfileFunction.Arn
