AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Configure Cognito Identity Provider (Google) and create a
  federated User Pool Client to enable Hosted UI sign-in.

Parameters:
  UserPoolId:
    Type: String
    Description: Existing Cognito User Pool Id to configure (e.g. us-east-1_xxx)

  CallbackURLs:
    Type: CommaDelimitedList
    Description: Comma separated list of callback URLs (e.g. https://app.example.com/auth/callback)

  LogoutURLs:
    Type: CommaDelimitedList
    Description: Comma separated list of sign-out URLs

  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID

  GoogleClientSecret:
    Type: String
    NoEcho: true
    Description: Google OAuth Client Secret

Resources:
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderName: Google
      ProviderType: Google
      UserPoolId: !Ref UserPoolId
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: "openid email profile"
      AttributeMapping:
        email: email
        username: sub

  FederatedUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: VISIT-JO-federated-client
      UserPoolId: !Ref UserPoolId
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      CallbackURLs: !Ref CallbackURLs
      LogoutURLs: !Ref LogoutURLs
      SupportedIdentityProviders:
        - COGNITO
        - Google
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  UserPoolClientId:
    Description: The new federated App Client id. Update frontend runtime with this.
    Value: !Ref FederatedUserPoolClient

  GoogleProviderName:
    Description: The Cognito provider name for Google (useful for confirmation)
    Value: !GetAtt GoogleIdentityProvider.ProviderName


